In [1]:
import torch

In [2]:
aa=torch.tensor([[1,2,3],[4,5,6]])

In [3]:
aa

tensor([[1, 2, 3],
        [4, 5, 6]])

In [6]:
bb=torch.tensor([9,95,69])

In [7]:
bb

tensor([ 9, 95, 69])

In [8]:
aa[1]=bb

In [9]:
aa

tensor([[ 1,  2,  3],
        [ 9, 95, 69]])

In [10]:
bb

tensor([ 9, 95, 69])

In [11]:
bb=torch.tensor([222,222,222])

In [12]:
bb

tensor([222, 222, 222])

In [13]:
aa

tensor([[ 1,  2,  3],
        [ 9, 95, 69]])

In [15]:
aa[1]=bb

In [16]:
aa

tensor([[  1,   2,   3],
        [222, 222, 222]])

In [17]:
bb

tensor([222, 222, 222])

In [18]:
aa[1]=torch.ones(3)

In [19]:
aa

tensor([[1, 2, 3],
        [1, 1, 1]])

In [21]:
aa=torch.ones(3,3)

In [22]:
aa

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [23]:
bb=aa

In [24]:
bb

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [25]:
aa=torch.zeros(3,3)

In [26]:
bb

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [27]:
aa

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [28]:
aa=torch.ones(3,4)

In [29]:
bb=aa

In [31]:
bb[0]=bb[0]+1

In [32]:
bb

tensor([[2., 2., 2., 2.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [33]:
aa

tensor([[2., 2., 2., 2.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [34]:
aa=torch.tensor([1,2,3])

In [35]:
bb=torch.ones(3,3)

In [36]:
bb[0]=aa

In [37]:
bb

tensor([[1., 2., 3.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [38]:
id(bb[0])==id(aa)

False

In [39]:
def rrr(tensor):
    print(tensor)

In [40]:
rrr(torch.ones(3)*(-1))

tensor([-1., -1., -1.])


In [5]:
a=torch.tensor([[1,2,3],[4,5,6],[7,8,9]])

In [6]:
a

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [10]:
shuffle_index= torch.randperm(3)

In [11]:
shuffle_index

tensor([0, 2, 1])

In [12]:
a[shuffle_index]

tensor([[1, 2, 3],
        [7, 8, 9],
        [4, 5, 6]])

In [16]:
a[0:3*7//10]

tensor([[1, 2, 3],
        [4, 5, 6]])