In [ ]:
## 前期w(惯性) 个体极值c1 最好大一点  后期w C1最好小一点
## 加入随机因素  前后期速度的变化 
# 如何避免局部最优 

In [1]:
import torch

In [3]:
a=torch.tensor([1,2,3,4])

In [10]:
a.shape[0]

4

In [19]:
def initialization(SearchAgents_no, dim, ub, lb):
    #     SearchAgents_no 为种群数量
    # Boundary_no = ub.shape[0]   ##比如ub [1,1,1]
    aa=torch.rand(SearchAgents_no,dim)
    print(aa)
    print(ub,lb)
    Positions=aa*(ub-lb)+lb
    print(Positions)
    return Positions


In [23]:
pos=initialization(10,5,torch.tensor([5,1,1,1,1]),torch.tensor([0,0,0,0,0]))

tensor([[0.7691, 0.2474, 0.3736, 0.4358, 0.6140],
        [0.3880, 0.3623, 0.2125, 0.8146, 0.3226],
        [0.7151, 0.6879, 0.1587, 0.4722, 0.8136],
        [0.0809, 0.9053, 0.2089, 0.9044, 0.0222],
        [0.7914, 0.4256, 0.8623, 0.2167, 0.5200],
        [0.6377, 0.2948, 0.7035, 0.6333, 0.1577],
        [0.5527, 0.8632, 0.7848, 0.3854, 0.0140],
        [0.2455, 0.1262, 0.5956, 0.9498, 0.3975],
        [0.0413, 0.9338, 0.1056, 0.8458, 0.8129],
        [0.9411, 0.8538, 0.1335, 0.1026, 0.0312]])
tensor([5, 1, 1, 1, 1]) tensor([0, 0, 0, 0, 0])
tensor([[3.8457, 0.2474, 0.3736, 0.4358, 0.6140],
        [1.9402, 0.3623, 0.2125, 0.8146, 0.3226],
        [3.5756, 0.6879, 0.1587, 0.4722, 0.8136],
        [0.4045, 0.9053, 0.2089, 0.9044, 0.0222],
        [3.9569, 0.4256, 0.8623, 0.2167, 0.5200],
        [3.1885, 0.2948, 0.7035, 0.6333, 0.1577],
        [2.7635, 0.8632, 0.7848, 0.3854, 0.0140],
        [1.2276, 0.1262, 0.5956, 0.9498, 0.3975],
        [0.2066, 0.9338, 0.1056, 0.8458, 0.8129],
 

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [24]:
torch.zeros(10,1)

tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]])

In [53]:
a=torch.tensor([[1,2,3],[2,3,4]])

In [32]:
a

tensor([[1, 2, 3],
        [2, 3, 4]])

In [35]:
a[0].shape

torch.Size([3])

In [38]:
A=torch.tensor([False,True,False])

In [39]:
B=torch.tensor([True,False,False])

In [40]:
A+B

tensor([ True,  True, False])

In [41]:
C=torch.tensor([132,23,23])

In [46]:
~A*C

tensor([ 0,  0, 23])

In [47]:
a=[]

In [48]:
a[0]=1

IndexError: list assignment index out of range

In [49]:
bb=torch.inf

In [54]:
a<bb

tensor([[True, True, True],
        [True, True, True]])

In [61]:
import copy

In [62]:
aa=[1,2]

In [63]:
bb=aa

In [64]:
bb

[1, 2]

In [65]:
aa[0]=123

In [67]:
aaa=torch.tensor([1,2,3])

In [68]:
bbb=copy.deepcopy(aaa)

In [69]:
bbb


tensor([1, 2, 3])

In [71]:
2**(2.1)

4.2870938501451725

In [85]:
A=torch.rand(1).item()

In [87]:
type(A)

float

In [88]:
import math

In [89]:
math.exp(2)

7.38905609893065

In [91]:
2.27*2.27

5.1529

In [94]:
type(math.exp(1))

float

In [93]:
2.718281828459045*2.718281828459045

7.3890560989306495

In [95]:
math.cos(1)

0.5403023058681398

In [96]:
zz=torch.tensor([-1,-2,2,5])

In [97]:
zz

tensor([-1, -2,  2,  5])

In [102]:
aa=-zz.abs()

In [103]:
aa

tensor([-1, -2, -2, -5])

In [104]:
aa.abs()

tensor([1, 2, 2, 5])

In [119]:
(torch.rand(1).item()>=0.5)*2-1

-1

In [120]:
for i in range(1,10):
    print(i)

1
2
3
4
5
6
7
8
9
